from plumbum import local, cli
import pp_cli
from pp_cli import SRCPATHS
import logging
import yaml


class App(cli.Application):
    """Deletes extraneous files not generated by pipeline(s)."""

    def main(self, *args):
        pipename = self.parent.name
        readAndSetSrcPaths()
