#!/usr/bin/env python
try:
    from plumbum import local, FG, cli
except ImportError:
    print('Couldn\'t import plumbum')
    print(
        'Did you forget to load python environment? (e.g. source activate pnlpipe)')
import software
import logging
# logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)5s - %(name)s %(message)s', datefmt="%Y-%m-%d %H:%M")
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)5s - %(name)s:  %(message)s',
    datefmt="%Y-%m-%d %H:%M")
logger = logging.getLogger(__name__)

import pipelib_cli.subcmd
import pipelib_cli.cmd.soft


class App(cli.Application):
    def main(self, *args):
        if args:
            print("Unknown command {0!r}".format(args[0]))
            return 1
        if not self.nested_command:
            print("No command given")
            return 1  # error exit code


def classSoftwareFactory(name,
                         makeFn,
                         BaseClass=pipelib_cli.cmd.soft.SoftwareCommand):
    def wrapFunction(self, *args, **kwargs):
        return make(*args, **kwargs)

    newclass = type(name, (BaseClass, ), {"make": wrapFunction})
    return newclass


def pipelineModules():
    import pkgutil
    import pipelines
    from os.path import isfile
    for importer, modname, ispkg in pkgutil.iter_modules(pipelines.__path__):
        if modname.startswith('pipeline_'):
            yield importer.find_module(modname).load_module(modname)


def classFactory(name,
                 makePipelineFn,
                 statusFn,
                 defaultTarget,
                 BaseClass=pipelib_cli.subcmd.PipelineSubcommand):
    def wrappedMakePipeline(self, *args, **kwargs):
        return makePipelineFn(*args, **kwargs)

    paramsFile = local.path(name + '.params')
    newclass = type(name, (BaseClass, ), {"name": name,
                                          "makePipeline": wrappedMakePipeline,
                                          "makePipeline_orig": makePipelineFn,
                                          "paramsFile": paramsFile,
                                          "defaultTarget": defaultTarget})

    if statusFn:

        def wrappedStatus(self, *args, **kwargs):
            return statusFn(*args, **kwargs)

        setattr(newclass, 'status', wrappedStatus)
    return newclass


if __name__ == '__main__':
    import pipelib_cli.cmd.init
    import pipelib_cli.cmd.soft
    import pipelib_cli.cmd.export
    import pipelib_cli.subcmd.init
    import pipelib_cli.subcmd.make
    import pipelib_cli.subcmd.run
    import pipelib_cli.subcmd.status
    import pipelib_cli.subcmd.symlink
    import pipelib_cli.subcmd.ls
    import pipelib_cli.subcmd.missing
    import pipelib_cli.subcmd.keys

    App.subcommand("init", pipelib_cli.cmd.init.Init)
    App.subcommand("soft", pipelib_cli.cmd.soft.SoftwareCommand)
    App.subcommand("export", pipelib_cli.cmd.export.Export)

    for m in pipelineModules():
        name = m.__name__[9:]
        statusFn = getattr(m, 'status', None)
        defaultTarget = getattr(m, 'DEFAULT_TARGET', None)
        SubcommandClass = classFactory(name, m.makePipeline, statusFn,
                                       defaultTarget)
        App.subcommand(name, SubcommandClass)
        SubcommandClass.subcommand("run",     pipelib_cli.subcmd.run.Run)
        SubcommandClass.subcommand("make",    pipelib_cli.subcmd.make.Make)
        SubcommandClass.subcommand("init",    pipelib_cli.subcmd.init.Init)
        SubcommandClass.subcommand("symlink", pipelib_cli.subcmd.symlink.SymLink)
        SubcommandClass.subcommand("status",  pipelib_cli.subcmd.status.Status)
        SubcommandClass.subcommand("ls",      pipelib_cli.subcmd.ls.Ls)
        SubcommandClass.subcommand("missing", pipelib_cli.subcmd.missing.Missing)
        SubcommandClass.subcommand("keys",    pipelib_cli.subcmd.keys.Keys)

    App.run()
