#!/usr/bin/env bash

set -eu
SCRIPT=$(readlink -m $(type -p $0))
SCRIPTDIR=${SCRIPT%/*}
source "$SCRIPTDIR/util.sh"

usage() {
echo -e "
Masks <img> (including DWI's) with <mask>.

Usage:

    mask <img> <mask> <out>
"
}

isdwi() {
    unu head $1 | egrep -q 'dimension.*4'
}

centerfirst=false
#[[ $# -gt 0 && $1 == "-c" ]] && { centerfirst=true; shift; }
[[ $# -ne 3 || $1 == -h* || $1 == --h* ]] && { usage; exit 1; }
read -r img mask out <<<"$@"

tmp=$(mktemp -d)
tmpimg=$tmp/$(base $img)-tmp.nrrd
tmpmask=$tmp/$(base $mask)-tmp.nrrd
tmpout=$tmp/$(base $out)-tmp.nrrd

if [[ $img == *.nhdr || $img == *.nrrd ]] && isdwi $img; then
    log "Mask dwi '$img' with '$mask' to make '$out'"
    if $centerfirst; then
        log "Center the image and the mask first"
        run center.py -i $img -o $tmpimg
        run center.py -i $mask -o $tmpmask
        run "unu 3op ifelse -w 1 $tmpmask $tmpimg 0 | unu save -e gzip -f nrrd -o $out"
    else
        run "unu 3op ifelse -w 1 $mask $img 0 | unu save -e gzip -f nrrd -o $out"
    fi
    log_success "Made '$out'"
    exit 0
fi

log "Mask '$img' with '$mask' to make '$out'"
run ConvertBetweenFileFormats "$img" "$tmpimg" >/dev/null
run ConvertBetweenFileFormats "$mask" "$tmpmask" >/dev/null
if $centerfirst; then
    log "Center the image and the mask first"
    run center.py -i $tmpimg -o $tmpimg
    run center.py -i $tmpmask -o $tmpmask
fi
run "unu 3op ifelse -w 1 $tmpmask $tmpimg 0 | unu save -e gzip -f nrrd -o $tmpout"
run ConvertBetweenFileFormats "$tmpout" "$out" >/dev/null
log_success "Made '$out'"
