name: pnlpipe3

channels:
  - conda-forge

dependencies:
  - python=3.8
  - ipython
  - pytest
  - plumbum
  - future
  - numpy
  - pandas
  - vtk
  - cmake
  - nibabel
  - nilearn
  - dipy
  - pyyaml
  - psutil
  - csvkit
  - gcc_linux-64
  - gxx_linux-64
  - joblib
  - matplotlib
  - conda-build
  - luigi
  - sqlalchemy
  - dash
  - statsmodels
  - tensorflow
  - keras
  - scikit-image
  - h5py
  - git
  - pip
  - pip:
     - git+https://github.com/SlicerDMRI/whitematteranalysis.git
     - git+https://github.com/dstrohl/Python_log_indenter.git
     - git+https://github.com/mhe/pynrrd.git
     - git+https://github.com/pnlbwh/conversion.git
