name: pnlpipe3-gpu

channels:
    - conda-forge

dependencies:
    - python
    - ipython

    - tensorflow-gpu
    - cudnn
    - keras
    - torchvision
    - h5py

    - nibabel
    - luigi
    - plumbum
    - sqlalchemy
    - psutil
    - pip

    - pip:
        - prompt-toolkit
        - gputil
        - scikit-image
        - SimpleITK
        - dipy
        - torch
        - git+https://github.com/pnlbwh/conversion.git
        - git+https://github.com/MIC-DKFZ/batchgenerators#egg=batchgenerators


